updates to allele_age; now can work on subsites of individuals

diff --git a/bin/allele_age b/bin/allele_age
--- a/bin/allele_age
+++ b/bin/allele_age
@@ -10,15 +10,18 @@ show_help () {
   echo
   echo " usage: allele-age [options] <baseout>"
   echo "   where <baseout> is the base name of arg-sample output (specified with "
-  echo "   arg-sample -o). Creates a file called <baseout>.allele_ages.bed.gz."
+  echo "   arg-sample -o). Creates a file called <baseout>.allele_age.bed.gz."
   echo " OPTIONS:"
   echo "   -S <sites.gz>: For pre-phased data, use this sites file for every iteration"
   echo "   -s <startnum>: start with this MCMC rep of arg-sample (default: 0)"
   echo "   -e <endnum>  : end with this MCMC rep (default: stop when no file exists)"
-  echo "   -i <interval>: sampling interval (will be auto-detected from output if not"
-  echo "        specified)"
+  echo "   -i <interval>: interval betwen MCMC reps (will be auto-detected from output"
+  echo "        if not specified)"
   echo "   -r <region>  : region (in format START-END, 1-based, inclusive) to"
   echo "        pass to smc2bed (default: run on all coordinates)"
+  echo "   -b <hap_file>: only use lineages listed in hap_file"
+  echo "   -B <ind_file>: only use lineages from individuals listed in ind_file"
+  echo "        (assumes diploid naming convention <ind>_1 and <ind>_2)"
   echo "   -t <tmpdir >     : directory for temporary files"
   echo "        (by default a directory named .tmp_allele_age will be created"
   echo "        and deleted when run is finished)"
@@ -30,7 +33,9 @@ endnum=-1
 region=""
 sitesfile=""
 tmpdir=".tmp_allele_age"
-while getopts "s:i:e:r:h" opt; do
+hapFile=""
+indFile=""
+while getopts "S:s:i:e:r:b:B:h" opt; do
   case "$opt" in
   h)
     show_help
@@ -51,6 +56,20 @@ while getopts "s:i:e:r:h" opt; do
   r)
     region=$OPTARG
     ;;
+  b)
+    if [[ -n $indFile ]]; then
+        echo "Cannot use both -b and -B"
+        exit 1
+    fi
+    hapFile=$OPTARG
+    ;;
+  B)
+    if [[ -n $hapFile ]]; then
+        echo "Cannot use both -b and -B"
+        exit 1
+    fi
+    indFile=$OPTARG
+    ;;
   t)
     tmpdir=$OPTARG
     ;;
@@ -63,6 +82,7 @@ if [[ "$#" -ne 1 ]]; then
     show_help
     exit 1
 fi
+
 
 baseout=$1
 startfile=$baseout.$startnum.smc.gz
@@ -99,6 +119,30 @@ elif [[ ! -d $tmpdir ]]; then
     exit 1
 fi
 
+hapArg1=""
+hapArg2=""
+if [[ -n $hapFile ]]; then
+    hapArg1=="-i $hapFile"
+    hapArg2="--subset $hapFile"
+fi
+if [[ -n $indFile ]]; then
+    indArg="--subset-inds $indFile"
+    inds=`cat $indFile`
+    ( for ind in $inds; do
+        for i in 1 2; do
+	    echo ${ind}_$i
+	done
+      done ) > $tmpdir/tmp_haps.txt
+    hapArg1="-i $tmpdir/tmp_haps.txt"
+    hapArg2="--subset-inds $indFile"
+fi
+
+if [[ -n $hapArg1 && -n $sitesfile ]]; then
+    subsites $hapArg1 -s $sitesfile -o $tmpdir/tmp.sites
+    sitesfile=$tmpdir/tmp.sites
+fi
+
+
 num=$startnum
 regionarg=""
 if [[ -n $region ]]; then
@@ -110,6 +154,10 @@ while [[ 1 ]]; do
         useSites=$sitesfile
     else
         useSites=$baseout.$num.sites.gz
+	if [[ -n $hapArg1 && -e $useSites ]]; then
+	    subsites $hapArg1 -s $useSites -o $tmpdir/tmp.sites
+	    useSites=$tmpdir/tmp.sites
+	fi
     fi
     file=$baseout.$num.smc.gz
     if [[ ( $endnum -ne -1 && $num -gt $endnum) || ! -e $file || ! -e $useSites ]]; then
@@ -130,7 +178,7 @@ while [[ 1 ]]; do
     fi
     echo $num $file $useSites >> /dev/stderr
     arg-summarize --log-file $baseout.log --snp-file $tmpdir/tmp.sites.bed.gz \
-      -a $tmpdir/tmp.bed.gz $regionarg2 --allele-age | bgzip \
+      -a $tmpdir/tmp.bed.gz $regionarg2 --allele-age $hapArg $indArg | bgzip \
           > $tmpdir/$num.allele_age.bed.gz
     num=$(($num+$interval))
     rm -f $tmpdir/tmp.sites.bed.gz $tmpdir/tmp.bed.gz
@@ -138,13 +186,16 @@ while [[ 1 ]]; do
 done
 
 rm -f $tmpdir/tmp.sites.gz $tmpdir/tmp.bed.gz
+if [[ -n $hapArg1 ]]; then
+    rm -f $tmpdir/tmp.sites
+fi
 
 zcat $tmpdir/$startnum.allele_age.bed.gz | grep "^#" > $baseout.allele_age.bed
 ( for i in `seq $startnum $interval $num`; do
       zcat $tmpdir/$i.allele_age.bed.gz | grep -v "^#"
       rm -f $tmpdir/$i.allele_age.bed.gz
   done ) | sort-bed - >> $baseout.allele_age.bed
-bgzip $baseout.allele_age.bed
+bgzip -f $baseout.allele_age.bed
 
 if [[ $deleteTmpDir == 1 ]]; then
     rmdir $tmpdir
